INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('chikorita', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('chikorita', 'tomy', 'nuevo', 20.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('chikorita', 'tomy', 'nuevo 2', 30.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('bayleef', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('meganium', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('cyndaquil', 'tomy', NULL, 10.00, false, false, false, true);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('cyndaquil', 'tomy', 'nuevo 1', 20.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('cyndaquil', 'tomy', 'nuevo 2', 30.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('cyndaquil', 't_arts', 'sentado', 40.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('cyndaquil', 't_arts', 'batalla', 50.00, false, false, false, true);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('quilava', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('typhlosion', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('totodile', 'tomy', 'antiguo', 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('totodile', 'tomy', '2009', 20.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('totodile', 'tomy', 'nuevo', 30.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('totodile', 't_arts', 'flotador', 40.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('croconaw', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('croconaw', 'tomy', 'versión 2', 20.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('feraligatr', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('sentret', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('furret', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('hoothoot', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('noctowl', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('ledyba', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('spinarak', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('ariados', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('chinchou', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('pichu', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('pichu', 'tomy', '2009', 20.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('pichu', 'tomy', 'picoreja', 30.00, false, false, true, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('pichu', 't_arts', 'dormido', 40.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('pichu', 't_arts', 'feliz', 50.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('cleffa', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('cleffa', 't_arts', 'dormido', 20.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('cleffa', 't_arts', 'con hoja', 30.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('igglybuff', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('togepi', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('togepi', 't_arts', 'dormido', 20.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('togekiss', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('natu', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('xatu', 'tomy', NULL, 10.00, false, false, false, true);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('mareep', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('mareep', 't_arts', 'dormido', 20.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('flaaffy', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('ampharos', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('bellossom', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('marill', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('marill', 't_arts', 'dormido', 20.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('marill', 't_arts', 'ojos cerrados', 30.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('marill', 't_arts', 'sobre neumático', 40.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('marill', 't_arts', 'postre', 50.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('azumarill', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('sudowoodo', 'tomy', NULL, 10.00, false, false, false, true);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('politoed', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('hoppip', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('skiploom', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('jumpluff', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('aipom', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('aipom', 't_arts', 'sobre neumático', 20.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('sunkern', 'tomy', NULL, 10.00, false, false, false, true);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('sunflora', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('yanma', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('wooper', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('quagsire', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('quagsire', 't_arts', 'dormido', 20.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('espeon', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('espeon', 'tomy', 'v2', 20.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('espeon', 'tomy', 'nuevo', 30.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('espeon', 't_arts', 'sorprendido', 40.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('umbreon', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('umbreon', 'tomy', 'nuevo', 20.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('umbreon', 't_arts', 'sobre cojín', 30.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('slowking', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('slowking', 'tomy', 'v2', 20.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('unown', 'tomy', NULL, 10.00, false, false, false, true);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('wobbuffet', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('pineco', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('forretress', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('dunsparce', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('gligar', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('steelix', 'tomy', NULL, 10.00, false, false, false, true);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('snubbull', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('granbull', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('qwilfish', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('scizor', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('scizor', 'tomy', 'nuevo', 20.00, false, false, false, true);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('shuckle', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('heracross', 'tomy', NULL, 10.00, false, false, false, true);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('sneasel', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('teddiursa', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('teddiursa', 't_arts', 'cojín', 20.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('teddiursa', 't_arts', 'con miedo', 30.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('teddiursa', 't_arts', 'hojas', 40.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('ursaring', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('slugma', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('swinub', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('piloswine', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('corsola', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('corsola', 't_arts', 'con balón', 20.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('remoraid', 'tomy', NULL, 10.00, false, false, false, true);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('octillery', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('delibird', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('mantine', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('skarmory', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('houndour', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('houndoom', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('phanpy', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('donphan', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('stantler', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('smeargle', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('hitmontop', 'tomy', 'sin cola', 10.00, false, false, false, true);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('hitmontop', 'tomy', 'sin base', 20.00, false, false, false, true);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('smoochum', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('elekid', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('elekid', 'tomy', 'v2', 20.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('magby', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('blissey', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('raikou', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('entei', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('entei', 'tomy', 'brillo', 20.00, false, false, true, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('suicune', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('suicune', 'tomy', 'brillo', 20.00, false, false, true, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('larvitar', 'tomy', 'nuevo', 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('larvitar', 't_arts', 'cojín', 20.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('larvitar', 't_arts', 'dormido', 30.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('larvitar', 't_arts', 'diorama', 40.00, false, false, false, true);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('pupitar', 'tomy', NULL, 10.00, false, false, false, true);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('pupitar', 'tomy', 'nuevo', 20.00, false, false, false, true);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('tyranitar', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('lugia', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('lugia', 'tomy', 'brillo', 20.00, false, false, true, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('ho-oh', 'tomy', NULL, 10.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('ho-oh', 'tomy', 'ataque', 20.00, false, false, false, false);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('celebi', 'tomy', 'translúcido', 10.00, false, true, false, true);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('celebi', 'tomy', 'transparente', 20.00, false, true, false, true);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('celebi', 'tomy', 'shiny', 30.00, true, false, false, true);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('celebi', 'tomy', 'normal', 40.00, false, false, false, true);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('celebi', 'tomy', 'sentado', 50.00, false, false, false, true);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('celebi', 'tomy', 'brillante, sentado, sin base', 60.00, false, false, true, true);
INSERT INTO public.figures (pokemon_id, line, details, visual_order, is_shiny, is_clear, is_pearl, has_base) VALUES ('celebi', 't_arts', 'shiny, sobre nube', 70.00, true, false, false, true);
